name: minimal artifact example with container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:noble

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: echo "this is a valuable artifact in a container" > artifact.txt

    - name: Look for a report in workspace
      run: |
        echo "github.workspace = ${{github.workspace}}"
        find ${{github.workspace}} -name artifact.txt -ls || true

    - name: Look for a report in default location?
      run: |
        echo "github.workspace = ${{github.workspace}}"
        find . -name artifact.txt -ls || true

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifact.txt
