name: minimal artifact example in container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:noble

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        pwd
        ls -a
        mkdir chest
        mkdir other_chest
        echo "this is a valuable artifact inside a container" > artifact.txt
        echo "this is a valuable artifact in a chest inside a container" > chest/artifact.txt
        echo "this is a valuable artifact in another chest inside a container" > other_chest/artifact.txt

    - name: Look for artifacts in the github.workspace
      run: |
        echo "github.workspace = ${{github.workspace}}"
        find ${{github.workspace}} -name artifact.txt -ls || true

    - name: Look for artifacts in whatever is the default directory
      run: |
        echo "pwd : $(pwd)"
        echo "github.workspace = ${{github.workspace}}"
        find . -name artifact.txt -ls || true


    - uses: actions/upload-artifact@v4
      with:
        name: absolute artifact
        path: ${{github.workspace}}/artifact.txt

    - uses: actions/upload-artifact@v4
      with:
        name: absolute artifact in a chest
        path: ${{github.workspace}}/chest/artifact.txt

    - uses: actions/upload-artifact@v4
      with:
        name: relative artifact
        path: artifact.txt

    - uses: actions/upload-artifact@v4
      with:
        name: relative artifact in a chest
        path: chest/artifact.txt

    - uses: actions/upload-artifact@v4
      with:
        name: artifact in workspace chest
        path: other_chest/artifact.txt

    - uses: actions/upload-artifact@v4
      with:
        name: absolute artifact in workspace chest
        path: ${{github.workspace}}/other_chest/artifact.txt
